server:
  port: 8001

spring:
  application:
    name: iam-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: verYs3cret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

jwt:
  secret:
    use: qBTBqz3r/8hW+a1/KPkqQMgWfQTW3vw7E5+HKx4Vru4=
  issuer: BackendArchitectureLab
  audience: BackendArchitectureLab
  expiration-minutes: 1440

superuser:
  key: ${SUPERUSER_KEY:super_secret_key_change_in_production}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
