version: "3.9"
services:
  postgres:
    image: 'postgres:latest'
    environment:
        - 'POSTGRES_USER=postgres'
        - 'POSTGRES_PASSWORD=verYs3cret'
        - 'POSTGRES_DB=postgres'
        - 'POSTGRES_HOST_AUTH_METHOD=trust'
    ports:
        - '5432:5432'
  backend:
#    build: .


    image: backendapi0212
    container_name: backend_api_all
    depends_on:
      - postgres

    ports:
      - "8000:8000"
    networks:
      - backend_network
volumes:
  postgres_data:
networks:
  backend_network:


#  sqlserver:
#    image: 'mcr.microsoft.com/mssql/server:latest'
#    environment:
#      - 'ACCEPT_EULA=yes'
#      - 'MSSQL_PID=express'
#      - 'MSSQL_SA_PASSWORD=verYs3cret'
#    ports:
#      - '1433'
